---
abstract: 'concatenate and print JSON files'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PipeFilters
requires:
  JSON::XS: 0
  Moose: 0
  MooseX::Getopt: 0
resources:
  repository: git://github.com/rcaputo/app-pipefilter.git
version: 0.001
